project_id = "zkcvinrutvvtfeedsprt"

[functions.get-weather]
verify_jwt = false

[functions.weather-ai-chat]
verify_jwt = true

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false